language: php
sudo: false

cache:
    directories:
      - $HOME/.composer/cache

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    php: hhvm

before_script:
  - wget https://knowledge.rapidssl.com/library/VERISIGN/ALL_OTHER/RapidSSL%20Intermediate/RapidSSL_CA_bundle.pem -O /tmp/cacert.pem
#  - echo 'curl.cainfo = /tmp/cacert.pem' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpspec.yml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then composer require --no-update --dev henrikbjorn/phpspec-code-coverage "1.0.*@dev"; fi;'
  - composer update
after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script: php -d curl.cainfo=/tmp/cacert.pem vendor/bin/phpspec run -fpretty -v
#script: vendor/bin/phpspec run -fpretty -v
